### ISSUE TITLE
Using Filters in Lion 10.7

### ISSUE THREAD

**Issue by dkong** [joshcarr/Apple-Quartz-Filters#1]
In Lion, the *.qfilter files should be copied to the following location:

/Library/Filters

The filters will NOT show up in Preview if the files are copied to the user's folder (~/Library/Filters)

**Comment by andypiper** [comment]
Alternatively, in Mountain Lion, since there is no /Library/Filters folder by default, you can put them in /Library/PDF Services

**Comment by emetselaar** [comment]
Thanks for the tip guys

**Comment by joshcarr** [comment]
Updated README, thanks for the feedback.

**Comment by sebastienbarre** [comment]
Just for whoever reads this issue in the future. `Reduce File Size.qfilter` is actually in `/System/Library/Filters` on macOS Sierra. While it is tempting to put more filters there, this can't be done since that directory is protected (`sudo` won't help).

**Comment by sebastienbarre** [comment]
The drawback of putting the filters in `/Library/PDF Services` is that all filters will show up in the "PDF" pop-up menu found at the bottom of the Print dialog (where you will select "Open PDF in Preview"). For this reason I suggest keeping all these filters in a `Filters` sub-directory (e.g. `/Library/PDF Services/Filters`). This will only add one entry to the "PDF" menu (e.g. "Filters"), but the "Quartz Filter" menu will automatically visit the "Filters" sub-directory and populate itself.
