### ISSUE TITLE
Creates huge PDF file sizes under macOS Mojave

### ISSUE THREAD

**Issue by oliveratgithub** [joshcarr/Apple-Quartz-Filters#5]
Just installed and tested the filters on a 4.8 mb PDF under macOS Mojave 10.14 Beta (18A347e) - and the results are:

* using the "300 dpi - average quality" filter: a 340 mb PDF file
* using the "150 dpi - average quality (standard)" filter: a 125 mb PDF file

Can you look into this?

**Comment by joshcarr** [comment]
Hi, I don't have access to macOS Mojave 10.14 Beta. But would welcome a pull request if you want to track down the issue.

**Comment by oliveratgithub** [comment]
Unfortunately I‘m not a developer so I can‘t contribute a pull request, I‘m sorry.

**Comment by RenBart** [comment]
Hi, Thanks to Josh for these excellent Quartz-Filters! I want to let you know that Quartz-Filters work perfectly with OS Mojave 10.14.6. Thank you

**Comment by joshcarr** [comment]
Thanks for the update @RenBart !
