### ISSUE TITLE
no save as dialog show

### ISSUE THREAD

**Issue by sbarex** [joshcarr/Apple-Quartz-Filters#6]
On Mojave, when I select the filter from the print dialog on the pdf button the save as dialog box don't show.
The file is processed but I don't know where he is saved.

**Comment by joshcarr** [comment]
Thanks for opening the issue. I am super happy to review and merge a pull request if you can develop a fix.

**Comment by sbarex** [comment]
I think it's a feature/bug of macOS. 
Removing the executable attribute resolve partially the problem:
`$ chmod a-x /Library/PDF\ Services/Reduce\ to\ *`
then when using the filter a pdf is created on the desktop.
Before chmod, the files download and extracted from this repository had the executable attribute set and the pdf was created inside the temp folder `/private/var/folders/[random charactes]/`...

**Comment by joshcarr** [comment]
You could add a note to the README about this and I'll accept the PR.

**Comment by sbarex** [comment]
sorry but I don't know how use GitHub for PR...

**Comment by joshcarr** [comment]
Ok, if in the future you want to give it a try, here's some info: https://help.github.com/articles/creating-a-pull-request/

Closing for now.
